module.exports = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR', INVALID_ID_FORMAT: 'INVALID_ID_FORMAT',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS', AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID', AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED', PERMISSION_DENIED: 'PERMISSION_DENIED',
  TENANT_SCOPE_VIOLATION: 'TENANT_SCOPE_VIOLATION', EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  DUPLICATE_EMPLOYEE_CODE: 'DUPLICATE_EMPLOYEE_CODE', DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  ATTENDANCE_INVALID_TRANSITION: 'ATTENDANCE_INVALID_TRANSITION',
  ATTENDANCE_ALREADY_CLOCKED_IN: 'ATTENDANCE_ALREADY_CLOCKED_IN',
  LEAVE_DATE_INVALID: 'LEAVE_DATE_INVALID', LEAVE_OVERLAP: 'LEAVE_OVERLAP',
  LEAVE_INSUFFICIENT_BALANCE: 'LEAVE_INSUFFICIENT_BALANCE',
  REFERENCED_ENTITY_NOT_FOUND: 'REFERENCED_ENTITY_NOT_FOUND', INTERNAL_ERROR: 'INTERNAL_ERROR',
});
