import { useCallback, useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useSelector } from "react-redux";
import { Ban, BriefcaseBusiness, Building2, CalendarDays, Eye, FileDown, IndianRupee, KeyRound, List, MapPin, PencilLine, RefreshCw, Sparkles, ThumbsDown, ThumbsUp, UserPlus, UserRoundCheck, UsersRound, X } from "lucide-react";
import * as employees from "../../Services/apiCalling/employeeApis";
import * as leave from "../../Services/apiCalling/leaveApis";
import * as vendors from "../../Services/apiCalling/vendorJobApis";
import * as audit from "../../Services/apiCalling/auditApis";
import * as reports from "../../Services/apiCalling/reportApis";
import * as admin from "../../Services/apiCalling/adminApis";
import { EMPLOYMENT_STATUSES, JOB_PROCESSES, JOB_STATUSES, JOB_TYPES, REPORT_TYPES, SALARY_TYPES } from "../../constants/enums.constants";
import { ROLES } from "../../constants/roles.constants";
import useIdempotencyKey from "../../hooks/useIdempotencyKey";
import useObjectIdParam from "../../hooks/useObjectIdParam";
import { transitionResult, unwrapCollection } from "../custom/apiBridge";
import ResourceWorkspace from "../custom/ResourceWorkspace";
import { Button, DataTable, DateText, EmptyState, ErrorState, Field, Modal, Money, PageHeading, Skeleton, StatusBadge } from "../custom/ui";
import LeaveCalendar from "../leave/LeaveCalendar";
import CandidateSubmissionModal from "../crm/CandidateSubmissionModal";
import SalaryBreakdown, { DEFAULT_DEDUCTIONS, DEFAULT_EARNINGS, componentPayload } from "./SalaryBreakdown";

const PASSWORD_RULE = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{10,128}$/;
const employeeColumns = [{ key: "employeeCode", label: "Code" }, { key: "firstName", label: "Employee", render: (v, r) => r.displayName || [v, r.lastName].filter(Boolean).join(" ") || r.email }, { key: "department", label: "Department" }, { key: "designation", label: "Designation" }, { key: "salaryType", label: "Salary type", render: StatusBadge }, { key: "employmentStatus", label: "Status", render: StatusBadge }];
const employeeCreateFields = [
  { type:"section", label:"Personal & work details", helper:"Identity and employment information." },
  { name:"employeeCode", label:"Employee code", required:true, placeholder:"e.g. EMP-001" }, { name:"workEmail", label:"Work email", type:"email", required:true, placeholder:"name@company.com" },
  { name:"firstName", label:"First name", required:true }, { name:"lastName", label:"Last name", required:true },
  { name:"phone", label:"Phone number", type:"tel", inputMode:"tel", required:true, placeholder:"e.g. +91 98765 43210" }, { name:"qualification", label:"Qualification", required:true, placeholder:"e.g. B.Tech in Computer Science" },
  { name:"designation", label:"Designation", required:true }, { name:"department", label:"Department", required:true }, { name:"joiningDate", label:"Joining date", type:"date", required:true },
  { type:"section", label:"Bank details", helper:"Account number, PAN and Aadhaar are encrypted before storage." },
  { name:"accountHolder", label:"Account holder", required:true, placeholder:"e.g. Darshan Kumar", autoComplete:"name" }, { name:"bankName", label:"Bank name", required:true, placeholder:"e.g. State Bank of India" },
  { name:"accountNumber", label:"Account number", inputMode:"numeric", required:true, placeholder:"e.g. 123456789012", autoComplete:"off" }, { name:"ifscOrRouting", label:"IFSC", required:true, placeholder:"e.g. SBIN0001234", autoComplete:"off" },
  { name:"pan", label:"PAN number", required:true, placeholder:"e.g. ABCDE1234F", autoComplete:"off" }, { name:"aadhaar", label:"Aadhaar number", inputMode:"numeric", required:true, placeholder:"e.g. 1234 5678 9012", autoComplete:"off" },
  { type:"section", label:"Salary", helper:"Compensation values are stored as precise decimal amounts." },
  { name:"salaryType", label:"Salary type", type:"select", options:SALARY_TYPES, required:true },
  { name:"monthlyCtc", label:"Monthly salary / CTC", type:"number", inputMode:"decimal", step:"0.01", required:true, placeholder:"e.g. 45000", showWhen:(form)=>form.salaryType==="SALARIED" },
  { name:"takeHomeSalary", label:"Take home salary", type:"number", inputMode:"decimal", step:"0.01", required:true, placeholder:"e.g. 38000", showWhen:(form)=>form.salaryType==="SALARIED" },
  { name:"hourlyRate", label:"Hourly rate", type:"number", inputMode:"decimal", step:"0.01", required:true, showWhen:(form)=>form.salaryType==="HOURLY" },
  { name:"itJoiningRate", label:"Amount per IT joining", type:"number", inputMode:"decimal", step:"0.01", required:true, placeholder:"e.g. 8000", helper:"Paid for each candidate who joins an IT job opening.", showWhen:(form)=>form.salaryType==="PER_JOINING" },
  { name:"nonItJoiningRate", label:"Amount per non-IT joining", type:"number", inputMode:"decimal", step:"0.01", required:true, placeholder:"e.g. 5000", helper:"Paid for each candidate who joins a non-IT job opening.", showWhen:(form)=>form.salaryType==="PER_JOINING" },
  { name:"salaryComponents", type:"custom", span:2, initial:{ earnings:DEFAULT_EARNINGS, deductions:DEFAULT_DEDUCTIONS }, showWhen:(form)=>form.salaryType==="SALARIED",
    render:(form,setForm)=><SalaryBreakdown earnings={form.salaryComponents?.earnings||[]} deductions={form.salaryComponents?.deductions||[]} onChange={(value)=>setForm(current=>({...current,salaryComponents:value}))}/> },
  { type:"section", label:"Account access", helper:"Optionally create a recruiter login for this employee." },
  { name:"createRecruiterAccount", label:"Create recruiter login", type:"checkbox", span:2 }, { name:"temporaryPassword", label:"Recruiter temporary password", type:"password", required:true, showWhen:(form)=>form.createRecruiterAccount, helper:"The recruiter must change this password after signing in." },
];
const employeeCreatePayload = ({createRecruiterAccount,temporaryPassword,accountHolder,bankName,accountNumber,ifscOrRouting,pan,aadhaar,salaryComponents,...employee}) => ({
  ...Object.fromEntries(Object.entries(employee).filter(([,value])=>value!=="")),
  bankDetails:Object.fromEntries(Object.entries({accountHolder,bankName,accountNumber,ifscOrRouting,pan,aadhaar}).filter(([,value])=>value!=="")),
  ...(employee.salaryType==="SALARIED"?{salaryComponents:{earnings:componentPayload(salaryComponents?.earnings),deductions:componentPayload(salaryComponents?.deductions)}}:{}),
  ...(createRecruiterAccount?{recruiterAccount:{temporaryPassword}}:{}),
});
export function EmployeesWorkspace() {
  const navigate = useNavigate();
  const [statusDialog,setStatusDialog]=useState(); const [statusForm,setStatusForm]=useState({employmentStatus:"ACTIVE",terminationDate:"",reason:""}); const [busy,setBusy]=useState(false); const [actionError,setActionError]=useState("");
  const openStatus=(row,reload)=>{setStatusForm({employmentStatus:row.employmentStatus||"ACTIVE",terminationDate:String(row.terminationDate||"").slice(0,10),reason:""});setActionError("");setStatusDialog({row,reload});};
  const saveStatus=async(event)=>{event.preventDefault();if(!statusDialog)return;setBusy(true);setActionError("");try{transitionResult(await employees.handleUpdateEmployeeStatus(statusDialog.row._id,{employmentStatus:statusForm.employmentStatus,reason:statusForm.reason,...(statusForm.employmentStatus==="TERMINATED"&&statusForm.terminationDate?{terminationDate:statusForm.terminationDate}:{})}));const reload=statusDialog.reload;setStatusDialog();await reload();}catch(error){setActionError(error.message);}finally{setBusy(false);}};
  const employeeName=statusDialog?.row?.displayName||[statusDialog?.row?.firstName,statusDialog?.row?.lastName].filter(Boolean).join(" ")||"this employee";
  return <>{actionError&&<div className="page-content page-content--notice"><ErrorState message={actionError}/></div>}<ResourceWorkspace api={employees} title="Employees" meta="Employee master" description="Manage employment profiles, access, compensation inputs, and lifecycle status." read={["handleGetEmployees"]} urlFilterKeys={["department","status"]} create={["handleCreateEmployee"]} createLabel="Add employee" createModalClassName="modal--employee" columns={employeeColumns} fields={employeeCreateFields} transformPayload={employeeCreatePayload} rowActions={(row,{reload}) => <div className="inline-actions job-row-actions"><Button variant="quiet" icon={Eye} onClick={() => navigate(`/employees/${row._id}`)}>View</Button><Button variant="quiet" icon={RefreshCw} onClick={()=>openStatus(row,reload)}>Change status</Button></div>} emptyDescription="Create the first employee profile to begin people operations." />
    <Modal open={Boolean(statusDialog)} onClose={()=>setStatusDialog()} title="Change employment status" description={`Update ${employeeName}’s lifecycle state. Terminating an employee revokes active recruiter sessions.`} footer={<><Button variant="secondary" onClick={()=>setStatusDialog()}>Cancel</Button><Button type="submit" form="employee-list-status-form" loading={busy}>Confirm status</Button></>}><form id="employee-list-status-form" className="form-stack" onSubmit={saveStatus}><Field label="Employment status"><select value={statusForm.employmentStatus} onChange={event=>setStatusForm({...statusForm,employmentStatus:event.target.value})}>{EMPLOYMENT_STATUSES.map(value=><option key={value}>{value}</option>)}</select></Field>{statusForm.employmentStatus==="TERMINATED"&&<Field label="Termination date"><input className="control" type="date" value={statusForm.terminationDate} onChange={event=>setStatusForm({...statusForm,terminationDate:event.target.value})}/></Field>}<Field label="Reason"><textarea value={statusForm.reason} required minLength={3} onChange={event=>setStatusForm({...statusForm,reason:event.target.value})}/></Field></form></Modal>
  </>;
}

export function EmployeeDetail({ employeeId = null, selfService = false }) {
  const user=useSelector(state=>state.auth.user); const isOwner=user?.role===ROLES.SUPER_ADMIN; const routeEmployee=useObjectIdParam("id",{enabled:!employeeId}); const id=employeeId||routeEmployee.id; const isValid=Boolean(id)&&(employeeId?true:routeEmployee.isValid); const [record, setRecord] = useState(); const [bank,setBank]=useState(); const [error, setError] = useState(""); const [dialog,setDialog]=useState(""); const [busy,setBusy]=useState(false); const [actionForm,setActionForm]=useState({employmentStatus:"ACTIVE",terminationDate:"",reason:"",temporaryPassword:""}); const [editForm,setEditForm]=useState({}); const {getKey,finish}=useIdempotencyKey();
  const load = useCallback(async () => { if (!isValid) return; try { const [employeeRecord,bankDetails]=await Promise.all([employees.handleGetEmployee(id),employees.handleGetEmployeeBankDetails(id)]);setRecord(employeeRecord);setBank(bankDetails);setError(""); } catch (e) { setError(e.message); } }, [id, isValid]);
  useEffect(() => { load(); }, [load]);
  const saveStatus=async(e)=>{e.preventDefault();setBusy(true);setError("");try{transitionResult(await employees.handleUpdateEmployeeStatus(id,{employmentStatus:actionForm.employmentStatus,reason:actionForm.reason,...(actionForm.employmentStatus==="TERMINATED"&&actionForm.terminationDate?{terminationDate:actionForm.terminationDate}:{})}));setDialog("");await load();}catch(err){setError(err.message);}finally{setBusy(false);}};
  const toggleRecruiter=async()=>{setBusy(true);try{const enabled=record.userId?.status!=="ACTIVE";transitionResult(await employees.handleUpdateEmployeeRecruiterAccess(id,{enabled,...(enabled&&actionForm.temporaryPassword?{temporaryPassword:actionForm.temporaryPassword}:{})}));setActionForm({...actionForm,temporaryPassword:""});await load();}catch(err){setError(err.message);}finally{setBusy(false);}};
  // Two modes behind one dialog: hand over a password now, or email a reset link
  // and never see it. `attempt` differs per mode so the idempotency key of a
  // failed attempt is never reused for the other one.
  const resetCredentials=async(mode)=>{
    setCredentialError("");
    const setting=mode==="password";
    if(setting){
      if(newPassword!==confirmPassword){setCredentialError("The two passwords do not match.");return;}
      if(!PASSWORD_RULE.test(newPassword)){setCredentialError("Use at least 10 characters with an uppercase letter, a lowercase letter, and a number.");return;}
    }
    const attempt=`credentials:${mode}:${id}`;setBusy(true);
    try{
      transitionResult(await employees.handleResetEmployeeCredentials(id,getKey(attempt),setting?{newPassword,confirmPassword}:{}));
      finish(attempt);setDialog("");setNewPassword("");setConfirmPassword("");
    }catch(err){setCredentialError(err.message);}finally{setBusy(false);}
  };
  const [newPassword,setNewPassword]=useState("");const [confirmPassword,setConfirmPassword]=useState("");const [credentialError,setCredentialError]=useState("");
  const openEdit=()=>{setEditForm({employeeCode:record.employeeCode||"",workEmail:record.workEmail||"",firstName:record.firstName||"",lastName:record.lastName||"",phone:record.phone||"",qualification:record.qualification||"",designation:record.designation||"",department:record.department||"",joiningDate:String(record.joiningDate||"").slice(0,10),salaryType:record.salaryType||"SALARIED",monthlyCtc:record.monthlyCtc||"",takeHomeSalary:record.takeHomeSalary||"",hourlyRate:record.hourlyRate||"",itJoiningRate:record.itJoiningRate||"",nonItJoiningRate:record.nonItJoiningRate||"",salaryComponents:{earnings:record.salaryComponents?.earnings?.map(row=>({label:row.label,amount:String(row.amount)}))||DEFAULT_EARNINGS,deductions:record.salaryComponents?.deductions?.map(row=>({label:row.label,amount:String(row.amount)}))||DEFAULT_DEDUCTIONS},accountHolder:bank?.accountHolder||"",bankName:bank?.bankName||"",ifscOrRouting:bank?.ifscOrRouting||"",accountNumber:"",pan:"",aadhaar:""});setDialog("edit");};
  const saveDetails=async(event)=>{event.preventDefault();setBusy(true);setError("");try{const {accountHolder,bankName,ifscOrRouting,accountNumber,pan,aadhaar,...profile}=editForm;const {salaryComponents,...rest}=profile;const salary=profile.salaryType==="SALARIED"?{monthlyCtc:profile.monthlyCtc,takeHomeSalary:profile.takeHomeSalary,hourlyRate:null,itJoiningRate:null,nonItJoiningRate:null,salaryComponents:{earnings:componentPayload(salaryComponents?.earnings),deductions:componentPayload(salaryComponents?.deductions)}}:profile.salaryType==="PER_JOINING"?{itJoiningRate:profile.itJoiningRate,nonItJoiningRate:profile.nonItJoiningRate,hourlyRate:null,monthlyCtc:null,takeHomeSalary:null}:{hourlyRate:profile.hourlyRate,monthlyCtc:null,takeHomeSalary:null,itJoiningRate:null,nonItJoiningRate:null};transitionResult(await employees.handleUpdateEmployee(id,{...rest,...salary}));transitionResult(await employees.handleUpdateEmployeeBankDetails(id,{accountHolder:accountHolder||null,bankName:bankName||null,ifscOrRouting:ifscOrRouting||null,...(accountNumber?{accountNumber}:{}),...(pan?{pan}:{}),...(aadhaar?{aadhaar}:{})}));setDialog("");await load();}catch(err){setError(err.message);}finally{setBusy(false);}};
  const employeeName=record?.displayName || [record?.firstName, record?.lastName].filter(Boolean).join(" ") || "Employee profile";
  return <main className="page-content"><PageHeading meta={selfService?"My profile":"Employee master"} title={employeeName} description={selfService?"Your employment, compensation, and securely stored payment information.":"Employment, compensation, and securely stored payment information."} actions={record&&isOwner?<div className="inline-actions"><Button icon={PencilLine} onClick={openEdit}>Edit details</Button><Button variant="secondary" icon={UserRoundCheck} loading={busy} onClick={()=>record.userId?.status==="ACTIVE"?toggleRecruiter():setDialog("recruiter")}>{record.userId?.status==="ACTIVE"?"Disable recruiter":"Enable recruiter"}</Button><Button variant="secondary" icon={Ban} onClick={()=>setDialog("status")}>Change status</Button>{record.userId&&<Button variant="quiet" icon={KeyRound} onClick={()=>setDialog("credentials")}>Reset credentials</Button>}</div>:null} />{error&&<ErrorState message={error} onRetry={load} />}{!error&&(!record ? <Skeleton rows={6} /> : <div className="employee-detail-sections">
    <section className="surface"><div className="section-header"><div><h2>Personal & work details</h2><p>Employee identity and role information.</p></div></div><div className="detail-grid">{[["Employee code",record.employeeCode],["Work email",record.workEmail],["Phone number",record.phone],["Qualification",record.qualification],["Department",record.department],["Designation",record.designation],["Joining date",<DateText value={record.joiningDate}/>],["Employment status",<StatusBadge value={record.employmentStatus}/>],["Recruiter login",record.userId?.status || "Not enabled"]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value || "—"}</strong></div>)}</div></section>
    <section className="surface"><div className="section-header"><div><h2>Salary</h2><p>Current compensation details.</p></div></div><div className="detail-grid">{[["Salary type",record.salaryType],...(record.salaryType==="PER_JOINING"?[["Amount per IT joining",record.itJoiningRate?<Money value={record.itJoiningRate}/>:"—"],["Amount per non-IT joining",record.nonItJoiningRate?<Money value={record.nonItJoiningRate}/>:"—"]]:record.salaryType==="HOURLY"?[["Hourly rate",record.hourlyRate?<Money value={record.hourlyRate}/>:"—"]]:[["Monthly salary / CTC",record.monthlyCtc?<Money value={record.monthlyCtc}/>:"—"],["Take home salary",record.takeHomeSalary?<Money value={record.takeHomeSalary}/>:"—"]])].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value || "—"}</strong></div>)}</div>
      {record.salaryType==="SALARIED"&&(record.salaryComponents?.earnings?.length||record.salaryComponents?.deductions?.length)?<div className="salary-components__summary">{[["Earnings",record.salaryComponents?.earnings||[]],["Deductions",record.salaryComponents?.deductions||[]]].map(([title,rows])=><div key={title}><strong>{title}</strong>{rows.length?rows.map(row=><span key={row.label}>{row.label}<b><Money value={row.amount}/></b></span>):<span className="muted">None</span>}</div>)}</div>:null}</section>
    <section className="surface"><div className="section-header"><div><h2>Bank details</h2><p>Sensitive identifiers are encrypted and displayed only in masked form.</p></div></div><div className="detail-grid">{[["Account holder",bank?.accountHolder],["Bank name",bank?.bankName],["Account number",bank?.accountNumber],["IFSC",bank?.ifscOrRouting],["PAN number",bank?.pan],["Aadhaar number",bank?.aadhaar]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value || "—"}</strong></div>)}</div></section>
  </div>)}
    <Modal className="modal--employee" open={dialog==="edit"} onClose={()=>setDialog("")} title="Edit employee details" description="Update profile, compensation, and bank information." footer={<><Button variant="secondary" onClick={()=>setDialog("")}>Cancel</Button><Button loading={busy} onClick={saveDetails}>Save changes</Button></>}><form className="form-grid" onSubmit={saveDetails}>
      <div className="form-section-title span-2"><strong>Personal & work details</strong><small>Identity and employment information.</small></div>
      <Field label="Employee code"><input className="control" required value={editForm.employeeCode||""} onChange={event=>setEditForm({...editForm,employeeCode:event.target.value})}/></Field><Field label="Work email"><input className="control" type="email" required value={editForm.workEmail||""} onChange={event=>setEditForm({...editForm,workEmail:event.target.value})}/></Field>
      <Field label="First name"><input className="control" required value={editForm.firstName||""} onChange={event=>setEditForm({...editForm,firstName:event.target.value})}/></Field><Field label="Last name"><input className="control" required value={editForm.lastName||""} onChange={event=>setEditForm({...editForm,lastName:event.target.value})}/></Field>
      <Field label="Phone number"><input className="control" type="tel" required value={editForm.phone||""} onChange={event=>setEditForm({...editForm,phone:event.target.value})}/></Field><Field label="Qualification"><input className="control" required value={editForm.qualification||""} onChange={event=>setEditForm({...editForm,qualification:event.target.value})}/></Field>
      <Field label="Designation"><input className="control" required value={editForm.designation||""} onChange={event=>setEditForm({...editForm,designation:event.target.value})}/></Field><Field label="Department"><input className="control" required value={editForm.department||""} onChange={event=>setEditForm({...editForm,department:event.target.value})}/></Field>
      <Field label="Joining date"><input className="control" type="date" required value={editForm.joiningDate||""} onChange={event=>setEditForm({...editForm,joiningDate:event.target.value})}/></Field>
      <div className="form-section-title span-2"><strong>Salary</strong><small>Current compensation details.</small></div>
      <Field label="Salary type"><select value={editForm.salaryType||"SALARIED"} onChange={event=>setEditForm({...editForm,salaryType:event.target.value})}>{SALARY_TYPES.map(value=><option key={value}>{value}</option>)}</select></Field>
      {editForm.salaryType==="SALARIED"?<><Field label="Monthly salary / CTC"><input className="control" type="number" min="0" step="0.01" required value={editForm.monthlyCtc||""} onChange={event=>setEditForm({...editForm,monthlyCtc:event.target.value})}/></Field><Field label="Take home salary"><input className="control" type="number" min="0" step="0.01" required value={editForm.takeHomeSalary||""} onChange={event=>setEditForm({...editForm,takeHomeSalary:event.target.value})}/></Field><div className="span-2"><SalaryBreakdown earnings={editForm.salaryComponents?.earnings||[]} deductions={editForm.salaryComponents?.deductions||[]} onChange={value=>setEditForm({...editForm,salaryComponents:value})}/></div></>:editForm.salaryType==="PER_JOINING"?<><Field label="Amount per IT joining" helper="Paid for each candidate who joins an IT job opening."><input className="control" type="number" min="0" step="0.01" required value={editForm.itJoiningRate||""} onChange={event=>setEditForm({...editForm,itJoiningRate:event.target.value})}/></Field><Field label="Amount per non-IT joining" helper="Paid for each candidate who joins a non-IT job opening."><input className="control" type="number" min="0" step="0.01" required value={editForm.nonItJoiningRate||""} onChange={event=>setEditForm({...editForm,nonItJoiningRate:event.target.value})}/></Field></>:<Field label="Hourly rate"><input className="control" type="number" min="0" step="0.01" required value={editForm.hourlyRate||""} onChange={event=>setEditForm({...editForm,hourlyRate:event.target.value})}/></Field>}
      <div className="form-section-title span-2"><strong>Bank details</strong><small>Leave sensitive fields blank to keep their current encrypted values.</small></div>
      <Field label="Account holder"><input className="control" value={editForm.accountHolder||""} onChange={event=>setEditForm({...editForm,accountHolder:event.target.value})}/></Field><Field label="Bank name"><input className="control" value={editForm.bankName||""} onChange={event=>setEditForm({...editForm,bankName:event.target.value})}/></Field>
      <Field label="IFSC"><input className="control" value={editForm.ifscOrRouting||""} onChange={event=>setEditForm({...editForm,ifscOrRouting:event.target.value})}/></Field><Field label="New account number" helper={bank?.accountNumber?`Current: ${bank.accountNumber}`:"Not provided"}><input className="control" inputMode="numeric" autoComplete="off" value={editForm.accountNumber||""} onChange={event=>setEditForm({...editForm,accountNumber:event.target.value})}/></Field>
      <Field label="New PAN number" helper={bank?.pan?`Current: ${bank.pan}`:"Not provided"}><input className="control" autoComplete="off" value={editForm.pan||""} onChange={event=>setEditForm({...editForm,pan:event.target.value})}/></Field><Field label="New Aadhaar number" helper={bank?.aadhaar?`Current: ${bank.aadhaar}`:"Not provided"}><input className="control" inputMode="numeric" autoComplete="off" value={editForm.aadhaar||""} onChange={event=>setEditForm({...editForm,aadhaar:event.target.value})}/></Field><button type="submit" hidden/>
    </form></Modal>
    <Modal open={dialog==="recruiter"} onClose={()=>setDialog("")} title="Enable recruiter access" description="Create or restore a fixed RECRUITER login for this employee." footer={<><Button variant="secondary" onClick={()=>setDialog("")}>Cancel</Button><Button loading={busy} onClick={async()=>{await toggleRecruiter();setDialog("");}}>Enable recruiter</Button></>}><Field label="Temporary password" helper="Required for a first-time recruiter account."><input className="control" type="password" value={actionForm.temporaryPassword} onChange={e=>setActionForm({...actionForm,temporaryPassword:e.target.value})}/></Field></Modal>
    <Modal open={dialog==="status"} onClose={()=>setDialog("")} title="Change employment status" description={`Update ${employeeName}’s lifecycle state. This may revoke active sessions.`} footer={<><Button variant="secondary" onClick={()=>setDialog("")}>Cancel</Button><Button loading={busy} onClick={saveStatus}>Confirm status</Button></>}><form className="form-stack" onSubmit={saveStatus}><Field label="Employment status"><select value={actionForm.employmentStatus} onChange={e=>setActionForm({...actionForm,employmentStatus:e.target.value})}>{EMPLOYMENT_STATUSES.map(value=><option key={value}>{value}</option>)}</select></Field>{actionForm.employmentStatus==="TERMINATED"&&<Field label="Termination date"><input className="control" type="date" value={actionForm.terminationDate} onChange={e=>setActionForm({...actionForm,terminationDate:e.target.value})}/></Field>}<Field label="Reason"><textarea value={actionForm.reason} required onChange={e=>setActionForm({...actionForm,reason:e.target.value})}/></Field><button type="submit" hidden/></form></Modal>
    <Modal open={dialog==="credentials"} onClose={()=>{setDialog("");setCredentialError("");setNewPassword("");setConfirmPassword("");}} title="Reset employee credentials" description={`Set a new password for ${employeeName}, or email them a reset link instead.`} footer={<><Button variant="secondary" onClick={()=>setDialog("")}>Cancel</Button><Button type="submit" form="credential-form" loading={busy} disabled={!newPassword||!confirmPassword}>Update password</Button></>}>
      <form id="credential-form" className="form-stack" onSubmit={(event)=>{event.preventDefault();resetCredentials("password");}}>
        <Field label="New password" helper="At least 10 characters, with an uppercase letter, a lowercase letter, and a number.">
          <input className="control" type="password" autoComplete="new-password" minLength={10} value={newPassword} onChange={event=>setNewPassword(event.target.value)} />
        </Field>
        <Field label="Re-enter new password" error={confirmPassword&&newPassword!==confirmPassword?"The two passwords do not match.":""}>
          <input className={`control ${confirmPassword&&newPassword!==confirmPassword?"control--error":""}`} type="password" autoComplete="new-password" value={confirmPassword} onChange={event=>setConfirmPassword(event.target.value)} />
        </Field>
        {credentialError&&<div className="auth-error" role="alert">{credentialError}</div>}
        <p className="dialog-copy">The employee is signed out everywhere and must choose their own password the next time they sign in, so this one only works once.</p>
        <button type="submit" hidden />
      </form>
      <div className="credential-alt">
        <div><strong>Prefer not to know their password?</strong><small>Emails a secure reset link to {record?.userId?.email||"the employee"} instead.</small></div>
        <Button variant="quiet" loading={busy} onClick={()=>resetCredentials("link")}>Send reset link</Button>
      </div>
    </Modal>
  </main>;
}

export function MyProfile() {
  const employeeId=useSelector(state=>state.auth.user?.employee?._id||state.auth.user?.employee?.id);
  return employeeId?<EmployeeDetail employeeId={employeeId} selfService/>:<main className="page-content"><ErrorState message="Your login is not linked to an employee profile."/></main>;
}

const leaveEmployeeName = (row) => { const employee=row?.employeeId||row?.employee; return employee&&typeof employee==="object"?[employee.firstName,employee.lastName].filter(Boolean).join(" ")||employee.employeeCode||"—":row?.employeeName||"—"; };
const leaveColumns = [{ key: "employeeId", label: "Employee", render: (_value,row) => leaveEmployeeName(row) }, { key: "startDate", label: "From", render: DateText }, { key: "endDate", label: "To", render: DateText }, { key: "reason", label: "Reason" }, { key: "status", label: "Status", render: StatusBadge }];
export function MyLeaveWorkspace() {
  const [types,setTypes]=useState([]); const [cancel,setCancel]=useState(); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [showCalendar,setShowCalendar]=useState(false);
  useEffect(()=>{let active=true;leave.handleGetLeaveTypes().then(data=>{if(active)setTypes(unwrapCollection(data).items);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  const cancelRequest=async(reload)=>{setBusy(true);setError("");try{transitionResult(await leave.handleCancelLeave(cancel._id,{reason}));setCancel();setReason("");await reload();}catch(e){setError(e.message);}finally{setBusy(false);}};
  return <>{error&&<div className="page-content page-content--notice"><ErrorState message={error}/></div>}{showCalendar?<main className="page-content"><PageHeading meta="My leave history" title="My leave calendar" description="Review your leave requests and their status by month." actions={<Button variant="secondary" icon={List} onClick={()=>setShowCalendar(false)}>Back to leave list</Button>}/><LeaveCalendar ownOnly/></main>:<ResourceWorkspace api={leave} title="My leave" meta="Time away" description="Request leave and follow each decision from the approval queue." read={["handleGetMyLeave"]} create={["handleSubmitLeave"]} createLabel="Request leave" secondary={<Button variant="secondary" icon={CalendarDays} onClick={()=>setShowCalendar(true)}>Leave calendar</Button>} columns={leaveColumns} fields={[{ name: "leaveTypeId", label: "Leave type", type:"select", options:types.map(type=>({value:type._id,label:type.name})), required: true }, { name: "startDate", label: "Start date", type: "date", required: true }, { name: "endDate", label: "End date", type: "date", required: true }, { name: "reason", label: "Reason", type: "textarea", span: 2 }]} rowActions={(row,{reload})=>row.status==="PENDING"?<Button variant="danger" onClick={()=>setCancel({...row,reload})}>Cancel request</Button>:null} emptyDescription="Your leave requests will appear here." />}
    <Modal open={Boolean(cancel)} onClose={()=>setCancel()} title="Cancel leave request" description="The request will remain in your history with a cancelled status." footer={<><Button variant="secondary" onClick={()=>setCancel()}>Keep request</Button><Button variant="danger" loading={busy} disabled={!reason.trim()} onClick={()=>cancelRequest(cancel.reload)}>Cancel leave</Button></>}><Field label="Reason" helper="Required for a clear approval trail"><textarea value={reason} required onChange={e=>setReason(e.target.value)}/></Field></Modal></>;
}
const LEAVE_QUEUE_FILTER_KEYS = ["status", "employeeId", "from", "to"];

export function LeaveQueueWorkspace() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [decision,setDecision]=useState(); const [note,setNote]=useState(""); const [busy,setBusy]=useState(false); const [showCalendar,setShowCalendar]=useState(false);
  const filterKey = JSON.stringify(Object.fromEntries(LEAVE_QUEUE_FILTER_KEYS.map((key) => [key, searchParams.get(key) || ""]).filter(([, value]) => value)));
  const clearFilter = (key) => setSearchParams((current) => { const next = new URLSearchParams(current); next.delete(key); return next; }, { replace: true });
  const load = useCallback(async () => { setLoading(true); try { setRows(unwrapCollection(await leave.handleGetLeaveQueue({ status: "PENDING", ...JSON.parse(filterKey), page: 1, limit: 50 })).items); setError(""); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [filterKey]);
  useEffect(() => { load(); }, [load]);
  const act = async () => { setBusy(true);try { transitionResult(await (decision.approve ? leave.handleApproveLeave(decision.row._id, note ? { note } : {}) : leave.handleRejectLeave(decision.row._id, { note })));setDecision();setNote("");await load(); } catch (e) { setError(e.message); } finally{setBusy(false);} };
  return <main className="page-content"><PageHeading meta={showCalendar?"Leave history":"Approvals"} title={showCalendar?"Leave calendar":"Leave queue"} description={showCalendar?"A monthly view of employee leave requests and their decision history.":"Pending requests requiring an explicit decision."} actions={<Button variant={showCalendar?"secondary":"primary"} icon={showCalendar?List:CalendarDays} onClick={()=>setShowCalendar(current=>!current)}>{showCalendar?"Back to queue":"Leave calendar"}</Button>}/>{showCalendar?<LeaveCalendar/>:<section className="surface">{Object.keys(JSON.parse(filterKey)).length ? <div className="toolbar">{Object.entries(JSON.parse(filterKey)).map(([key, value]) => <button type="button" className="crm-monitor-chip" key={key} onClick={() => clearFilter(key)} aria-label={`Remove the ${key} filter`}><small>{key}</small><b>{String(value).replaceAll("_", " ")}</b><X size={12} aria-hidden="true" /></button>)}</div> : null}{loading ? <Skeleton rows={6}/> : error ? <ErrorState message={error} onRetry={load}/> : rows.length ? <DataTable rows={rows} columns={leaveColumns} actions={(row)=><div className="inline-actions"><Button variant="quiet" icon={ThumbsUp} onClick={()=>setDecision({row,approve:true})}>Approve</Button><Button variant="danger" icon={ThumbsDown} onClick={()=>setDecision({row,approve:false})}>Reject</Button></div>}/> : <EmptyState title="The queue is clear" description="There are no pending leave requests."/>}</section>}<Modal open={Boolean(decision)} onClose={()=>setDecision()} title={decision?.approve?"Approve leave request":"Reject leave request"} description={`${leaveEmployeeName(decision?.row)} · ${decision?.row?.startDate||""} to ${decision?.row?.endDate||""}`} footer={<><Button variant="secondary" onClick={()=>setDecision()}>Cancel</Button><Button variant={decision?.approve?"primary":"danger"} loading={busy} disabled={!decision?.approve&&!note.trim()} onClick={act}>{decision?.approve?"Approve request":"Reject request"}</Button></>}><Field label={decision?.approve?"Decision note (optional)":"Reason for rejection"}><textarea value={note} required={!decision?.approve} onChange={e=>setNote(e.target.value)}/></Field></Modal></main>;
}

const vendorFields = [
  { type:"section", label:"Vendor details", helper:"Business identity and agreement information." },
  { name:"name", label:"Vendor name", required:true, placeholder:"e.g. Acme Staffing" },
  { name:"website", label:"Website", type:"url", required:true, placeholder:"https://example.com" },
  { name:"agreementDate", label:"Agreement date", type:"date", required:true },
  { name:"location", label:"Location", required:true, placeholder:"e.g. Pune, Maharashtra" },
  { name:"status", label:"Status", type:"select", options:["ACTIVE","INACTIVE"] },
  { name:"clauseDaysDefault", label:"Default clause days", type:"number", min:"0", max:"3650", placeholder:"e.g. 45" },
  { type:"section", label:"Primary contact", helper:"The main person to contact at this vendor." },
  { name:"contactName", label:"Contact person", placeholder:"Full name" },
  { name:"contactPhone", label:"Contact phone", type:"tel", inputMode:"tel" },
  { name:"contactEmail", label:"Contact email", type:"email", span:2 },
];
const vendorCreatePayload = ({contactName,contactPhone,contactEmail,...vendor}) => {
  const contactInfo=Object.fromEntries(Object.entries({name:contactName,phone:contactPhone,email:contactEmail}).filter(([,value])=>value!==""));
  return {...Object.fromEntries(Object.entries(vendor).filter(([,value])=>value!=="")),...(Object.keys(contactInfo).length?{contactInfo}:{})};
};

export function VendorsWorkspace() {
  const navigate=useNavigate();
  return <ResourceWorkspace api={vendors} title="Vendors" meta="Hiring partners" description="Maintain recruitment vendors, agreements, contacts, and default invoice clauses." read={["handleGetVendors"]} create={["handleCreateVendor"]} createLabel="Add vendor" columns={[{key:"name",label:"Vendor"},{key:"location",label:"Location"},{key:"status",label:"Status",render:StatusBadge},{key:"clauseDaysDefault",label:"Clause days",align:"right"}]} fields={vendorFields} transformPayload={vendorCreatePayload} rowActions={(row)=><Button variant="quiet" icon={Eye} onClick={()=>navigate(`/vendors/${row._id}`)}>View</Button>} />;
}

export function VendorDetail() {
  const {id,isValid}=useObjectIdParam();
  const [record,setRecord]=useState(); const [form,setForm]=useState({}); const [editing,setEditing]=useState(false); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const load=useCallback(async()=>{if(!isValid)return;setLoading(true);try{setRecord(await vendors.handleGetVendor(id));setError("");}catch(e){setError(e.message);}finally{setLoading(false);}},[id,isValid]);
  useEffect(()=>{load();},[load]);
  const openEdit=()=>{setForm({name:record.name||"",website:record.website||"",agreementDate:String(record.agreementDate||"").slice(0,10),location:record.location||"",status:record.status||"ACTIVE",clauseDaysDefault:record.clauseDaysDefault??"",contactName:record.contactInfo?.name||"",contactPhone:record.contactInfo?.phone||"",contactEmail:record.contactInfo?.email||""});setEditing(true);};
  const save=async(event)=>{event.preventDefault();setSaving(true);setError("");try{const {contactName,contactPhone,contactEmail,...details}=form;const contactInfo=Object.fromEntries(Object.entries({name:contactName,phone:contactPhone,email:contactEmail}).filter(([,value])=>value!==""));transitionResult(await vendors.handleUpdateVendor(id,{...details,website:details.website||null,agreementDate:details.agreementDate||null,location:details.location||null,contactInfo:Object.keys(contactInfo).length?contactInfo:null}));setEditing(false);await load();}catch(e){setError(e.message);}finally{setSaving(false);}};
  const contact=record?.contactInfo||{};
  return <main className="page-content"><PageHeading meta="Hiring partner" title={record?.name||"Vendor details"} description="Vendor agreement, contact, and recruitment partnership information." actions={record?<Button icon={PencilLine} onClick={openEdit}>Edit details</Button>:null}/>{error&&<ErrorState message={error} onRetry={load}/>} {!error&&(loading?<Skeleton rows={6}/>:record?<div className="employee-detail-sections">
    <section className="surface"><div className="section-header"><div><h2>Vendor details</h2><p>Business identity and agreement information.</p></div></div><div className="detail-grid">
      <div><span>Vendor name</span><strong>{record.name}</strong></div><div><span>Website</span><strong>{record.website?<a href={record.website} target="_blank" rel="noreferrer">{record.website}</a>:"—"}</strong></div><div><span>Location</span><strong>{record.location||"—"}</strong></div>
      <div><span>Agreement date</span><strong><DateText value={record.agreementDate}/></strong></div><div><span>Status</span><strong><StatusBadge value={record.status}/></strong></div><div><span>Default clause days</span><strong>{record.clauseDaysDefault??"—"}</strong></div>
    </div></section>
    <section className="surface"><div className="section-header"><div><h2>Primary contact</h2><p>The main person to contact at this vendor.</p></div></div><div className="detail-grid"><div><span>Contact person</span><strong>{contact.name||"—"}</strong></div><div><span>Contact phone</span><strong>{contact.phone||"—"}</strong></div><div><span>Contact email</span><strong>{contact.email?<a href={`mailto:${contact.email}`}>{contact.email}</a>:"—"}</strong></div></div></section>
  </div>:<EmptyState title="Vendor not found" description="This vendor is no longer available."/>)}
    <Modal className="modal--employee" open={editing} onClose={()=>setEditing(false)} title="Edit vendor details" description="Update the vendor agreement, location, and contact information." footer={<><Button variant="secondary" onClick={()=>setEditing(false)}>Cancel</Button><Button type="submit" form="vendor-edit-form" loading={saving}>Save changes</Button></>}><form id="vendor-edit-form" className="form-grid" onSubmit={save}>
      <div className="form-section-title span-2"><strong>Vendor details</strong><small>Business identity and agreement information.</small></div>
      <Field label="Vendor name"><input className="control" required value={form.name||""} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Website"><input className="control" type="url" required placeholder="https://example.com" value={form.website||""} onChange={e=>setForm({...form,website:e.target.value})}/></Field>
      <Field label="Agreement date"><input className="control" type="date" required value={form.agreementDate||""} onChange={e=>setForm({...form,agreementDate:e.target.value})}/></Field><Field label="Location"><input className="control" required value={form.location||""} onChange={e=>setForm({...form,location:e.target.value})}/></Field>
      <Field label="Status"><select value={form.status||"ACTIVE"} onChange={e=>setForm({...form,status:e.target.value})}>{["ACTIVE","INACTIVE"].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Default clause days"><input className="control" type="number" min="0" max="3650" value={form.clauseDaysDefault??""} onChange={e=>setForm({...form,clauseDaysDefault:e.target.value})}/></Field>
      <div className="form-section-title span-2"><strong>Primary contact</strong><small>The main person to contact at this vendor.</small></div>
      <Field label="Contact person"><input className="control" value={form.contactName||""} onChange={e=>setForm({...form,contactName:e.target.value})}/></Field><Field label="Contact phone"><input className="control" type="tel" value={form.contactPhone||""} onChange={e=>setForm({...form,contactPhone:e.target.value})}/></Field><Field label="Contact email" className="span-2"><input className="control" type="email" value={form.contactEmail||""} onChange={e=>setForm({...form,contactEmail:e.target.value})}/></Field><button type="submit" hidden/>
    </form></Modal>
  </main>;
}
const companyForJob = (job) => job.vendorId?.name || job.companyName || "—";
const jobColumns = [{key:"title",label:"Role"},{key:"companyName",label:"Company",render:(_value,row)=>companyForJob(row)},{key:"process",label:"Process",render:StatusBadge},{key:"jobType",label:"Type",render:StatusBadge},{key:"openings",label:"Openings",align:"center"},{key:"monthlyCtc",label:"Monthly CTC",align:"right",render:Money},{key:"clauseDays",label:"Clause days",align:"center"},{key:"status",label:"Status",render:StatusBadge}];
const jobFields = (vendorOptions) => [
  {type:"section",label:"Company & role",helper:"Start with the hiring company and the basics of the opening."},
  {name:"vendorId",label:"Saved vendor",type:"select",span:2,options:vendorOptions.map(v=>({value:v._id,label:v.name})),helper:"Select a vendor already in HRMS. Leave blank to enter a new company below."},
  {name:"companyName",label:"Company",span:2,required:true,placeholder:"e.g. Acme Technologies Pvt Ltd",showWhen:form=>!form.vendorId},
  {name:"title",label:"Role title",span:2,required:true,placeholder:"e.g. Customer Support Executive"},
  {name:"location",label:"Location",required:true,placeholder:"e.g. Bengaluru"},{name:"openings",label:"Number of openings",type:"number",min:"1",required:true,initial:"1"},
  {name:"process",label:"Process",type:"select",options:JOB_PROCESSES,required:true},{name:"jobType",label:"IT / Non-IT",type:"select",options:JOB_TYPES,required:true},
  {type:"section",label:"Candidate profile",helper:"Describe who will succeed in this role."},
  {name:"skills",label:"Skills",type:"textarea",span:2,required:true,placeholder:"List the skills needed for this role"},
  {name:"requirements",label:"Requirement",type:"textarea",span:2,required:true,placeholder:"Eligibility / requirements for this role"},
  {name:"description",label:"Role description",type:"textarea",span:2,placeholder:"Add responsibilities or any other useful role details"},
  {type:"section",label:"Compensation & terms",helper:"Vendor payment is visible only to administrators."},
  {name:"salaryRange",label:"Salary range",span:2,required:true,placeholder:"e.g. ₹30,000–₹45,000 monthly"},
  {name:"monthlyCtc",label:"CTC (monthly)",type:"number",inputMode:"decimal",step:"0.01",min:"0",required:true,placeholder:"e.g. 45000"},
  {name:"takeHomeSalary",label:"Take-home salary",type:"number",inputMode:"decimal",step:"0.01",min:"0",required:true,placeholder:"e.g. 38000"},
  {name:"clauseDays",label:"Clause days",type:"number",min:"0",max:"3650",required:true,placeholder:"e.g. 45"},
  {name:"vendorPayment",label:"Vendor payment (internal)",type:"number",inputMode:"decimal",step:"0.01",min:"0",helper:"Admin-only — never shown to candidates or employees."},
  {name:"status",label:"Opening status",type:"select",options:JOB_STATUSES,initial:"DRAFT"},
];
const normalizeJobPayload = (form) => {
  const clean=Object.fromEntries(Object.entries(form).filter(([,value])=>value!==""));
  if(clean.vendorId) clean.companyName=null; else clean.vendorId=null;
  return clean;
};
function JobFormFields({ fields, form, setForm }) {
  return fields.filter(field=>!field.showWhen||field.showWhen(form)).map(field=>field.type==="section"?<div className="form-section-title span-2" key={field.label}><strong>{field.label}</strong>{field.helper&&<small>{field.helper}</small>}</div>:<Field key={field.name} label={field.label} helper={field.helper} className={field.span===2?"span-2":""}>{field.type==="select"?<select value={form[field.name]??""} required={field.required} onChange={e=>setForm(current=>({...current,[field.name]:e.target.value}))}><option value="">Select {field.label.toLowerCase()}</option>{field.options?.map(option=><option key={typeof option==="string"?option:option.value} value={typeof option==="string"?option:option.value}>{typeof option==="string"?option.replaceAll("_"," "):option.label}</option>)}</select>:field.type==="textarea"?<textarea value={form[field.name]??""} required={field.required} placeholder={field.placeholder} onChange={e=>setForm(current=>({...current,[field.name]:e.target.value}))}/>:<input className="control" type={field.type||"text"} inputMode={field.inputMode} step={field.step} min={field.min} max={field.max} value={form[field.name]??""} required={field.required} placeholder={field.placeholder} onChange={e=>setForm(current=>({...current,[field.name]:e.target.value}))}/>}</Field>);
}
const displayJobValue = (value) => value == null || value === "" ? "—" : value;
function JobDetail({ icon:Icon, label, children, accent=false }) {
  return <div className={`job-detail ${accent?"job-detail--accent":""}`}><span className="job-detail__icon"><Icon size={17}/></span><div><small>{label}</small><strong>{displayJobValue(children)}</strong></div></div>;
}
export function JobsWorkspace({ activeOnly=false, assignedOnly=false }) {
  const user=useSelector(state=>state.auth.user);const isOwner=user?.role===ROLES.SUPER_ADMIN;
  const [vendorOptions,setVendorOptions]=useState([]);const [recruiters,setRecruiters]=useState([]);const [statusDialog,setStatusDialog]=useState();const [assignmentDialog,setAssignmentDialog]=useState();const [detailDialog,setDetailDialog]=useState();const [editDialog,setEditDialog]=useState();const [submissionJob,setSubmissionJob]=useState();const [editForm,setEditForm]=useState({});const [selectedRecruiters,setSelectedRecruiters]=useState([]);const [status,setStatus]=useState("DRAFT");const [busy,setBusy]=useState(false);const [actionError,setActionError]=useState("");
  useEffect(()=>{if(!isOwner)return;let active=true;Promise.all([vendors.handleGetVendors({page:1,limit:100,status:"ACTIVE"}),employees.handleGetEmployees({page:1,limit:100,status:"ACTIVE"})]).then(([vendorData,employeeData])=>{if(!active)return;setVendorOptions(unwrapCollection(vendorData).items);setRecruiters(unwrapCollection(employeeData).items.filter(employee=>employee.userId?.role===ROLES.RECRUITER&&employee.userId?.status==="ACTIVE"));}).catch(e=>{if(active)setActionError(e.message);});return()=>{active=false;};},[isOwner]);
  const updateStatus=async()=>{setBusy(true);try{transitionResult(await vendors.handleUpdateJobOpeningStatus(statusDialog.row._id,{status}));const reload=statusDialog.reload;setStatusDialog();await reload();}catch(e){setActionError(e.message);}finally{setBusy(false);}};
  const updateRecruiters=async()=>{setBusy(true);try{transitionResult(await vendors.handleUpdateJobOpeningRecruiters(assignmentDialog.row._id,{recruiterEmployeeIds:selectedRecruiters}));const reload=assignmentDialog.reload;setAssignmentDialog();await reload();}catch(e){setActionError(e.message);}finally{setBusy(false);}};
  const openEdit=(row,reload)=>{setEditForm({...Object.fromEntries(jobFields(vendorOptions).filter(field=>field.name).map(field=>[field.name,row[field.name]??""])),vendorId:row.vendorId?._id||row.vendorId||""});setEditDialog({row,reload});};
  const updateJob=async(event)=>{event.preventDefault();setBusy(true);setActionError("");try{transitionResult(await vendors.handleUpdateJobOpening(editDialog.row._id,normalizeJobPayload(editForm)));const reload=editDialog.reload;setEditDialog();await reload();}catch(e){setActionError(e.message);}finally{setBusy(false);}};
  const openAssignments=(row,reload)=>{const available=new Set(recruiters.map(recruiter=>String(recruiter._id)));setSelectedRecruiters((row.assignedRecruiterIds||[]).map(item=>String(item?._id||item)).filter(id=>available.has(id)));setAssignmentDialog({row,reload});};
  const title=assignedOnly?"Assigned jobs":activeOnly?"Active jobs":"Job openings";
  return <>{actionError&&<div className="page-content page-content--notice"><ErrorState message={actionError}/></div>}<ResourceWorkspace api={vendors} title={title} meta="Recruitment" description={assignedOnly?"Jobs assigned to you, including existing pipelines for jobs on hold or closed.":activeOnly?"Open roles available for candidate sourcing.":"Create jobs and control recruiter assignments."} read={["handleGetJobOpenings"]} create={isOwner&&!activeOnly&&!assignedOnly?["handleCreateJobOpening"]:[]} createModalClassName="modal--job-form" className="jobs-workspace" columns={jobColumns} query={activeOnly?{status:"ACTIVE"}:{}} fields={jobFields(vendorOptions)} transformPayload={normalizeJobPayload} rowActions={(row,{reload})=><div className="inline-actions job-row-actions"><Button variant="quiet" icon={Eye} onClick={()=>setDetailDialog(row)}>View</Button>{row.status==="ACTIVE"&&(assignedOnly||isOwner)&&<Button variant="quiet" icon={UserPlus} onClick={()=>setSubmissionJob(row)}>Submit candidate</Button>}{isOwner&&!activeOnly&&!assignedOnly&&<><Button variant="quiet" icon={PencilLine} onClick={()=>openEdit(row,reload)}>Edit</Button><Button variant="quiet" icon={RefreshCw} onClick={()=>{setStatus(row.status);setStatusDialog({row,reload});}}>Change status</Button><Button variant="quiet" icon={UsersRound} onClick={()=>openAssignments(row,reload)}>Assign recruiters</Button></>}</div>} emptyDescription="No matching job openings are available." />
    <Modal className="modal--job-view" open={Boolean(detailDialog)} onClose={()=>setDetailDialog()} title={detailDialog?.title||"Job details"} description="Complete opening overview"><div className="job-view">
      <section className="job-view__hero"><div className="job-view__company"><span><Building2 size={22}/></span><div><small>Hiring company</small><strong>{companyForJob(detailDialog||{})}</strong><p><MapPin size={13}/>{detailDialog?.location||"Location not specified"}</p></div></div><div className="job-view__badges"><StatusBadge value={detailDialog?.status}/><StatusBadge value={detailDialog?.process}/><StatusBadge value={detailDialog?.jobType}/></div></section>
      <section className="job-view__section"><header><BriefcaseBusiness size={18}/><div><h3>Role overview</h3><p>Position details and hiring terms</p></div></header><div className={isOwner?"job-view__grid":"job-view__grid job-view__grid--two"}><JobDetail icon={UsersRound} label="Openings">{detailDialog?.openings}</JobDetail>{isOwner&&<JobDetail icon={CalendarDays} label="Clause days">{detailDialog?.clauseDays}</JobDetail>}<JobDetail icon={Sparkles} label="Skills">{detailDialog?.skills}</JobDetail></div></section>
      <section className="job-view__section job-view__section--money"><header><IndianRupee size={18}/><div><h3>Compensation</h3><p>Monthly candidate compensation and commercial terms</p></div></header><div className="job-view__grid"><JobDetail icon={IndianRupee} label="Salary range">{detailDialog?.salaryRange}</JobDetail><JobDetail icon={IndianRupee} label="Monthly CTC">{detailDialog?.monthlyCtc?<Money value={detailDialog.monthlyCtc}/>:"—"}</JobDetail><JobDetail icon={IndianRupee} label="Take-home salary">{detailDialog?.takeHomeSalary?<Money value={detailDialog.takeHomeSalary}/>:"—"}</JobDetail>{isOwner&&<JobDetail icon={IndianRupee} label="Vendor payment · Internal" accent>{detailDialog?.vendorPayment?<Money value={detailDialog.vendorPayment}/>:"—"}</JobDetail>}</div></section>
      <section className="job-view__copy"><div><span>Eligibility & requirements</span><p>{detailDialog?.requirements||"No requirements added."}</p></div>{detailDialog?.description&&<div><span>Role description</span><p>{detailDialog.description}</p></div>}</section>
    </div></Modal>
    <Modal className="modal--job-form" open={Boolean(editDialog)} onClose={()=>setEditDialog()} title="Edit job opening" description="Update the company, role requirements, compensation, and terms." footer={<><Button variant="secondary" onClick={()=>setEditDialog()}>Cancel</Button><Button type="submit" form="job-edit-form" loading={busy}>Save changes</Button></>}><form id="job-edit-form" className="form-grid" onSubmit={updateJob}><JobFormFields fields={jobFields(vendorOptions)} form={editForm} setForm={setEditForm}/><button type="submit" hidden/></form></Modal>
    <Modal open={Boolean(statusDialog)} onClose={()=>setStatusDialog()} title="Change job status" description="Only active jobs accept new candidates. Existing assigned pipelines remain accessible on hold or closed." footer={<><Button variant="secondary" onClick={()=>setStatusDialog()}>Cancel</Button><Button loading={busy} onClick={updateStatus}>Update status</Button></>}><Field label="Job status"><select value={status} onChange={e=>setStatus(e.target.value)}>{JOB_STATUSES.map(value=><option key={value}>{value}</option>)}</select></Field></Modal>
    <Modal open={Boolean(assignmentDialog)} onClose={()=>setAssignmentDialog()} title="Assign recruiters" description="Replacing this list immediately removes unassigned recruiters from the job and its candidates." footer={<><Button variant="secondary" onClick={()=>setAssignmentDialog()}>Cancel</Button><Button loading={busy} onClick={updateRecruiters}>Save assignments</Button></>}><div className="form-stack">{recruiters.length?recruiters.map(recruiter=>{const id=String(recruiter._id);return <label className="check-field" key={id}><input type="checkbox" checked={selectedRecruiters.includes(id)} onChange={event=>setSelectedRecruiters(current=>event.target.checked?[...current,id]:current.filter(value=>value!==id))}/><span><strong>{recruiter.displayName||`${recruiter.firstName} ${recruiter.lastName}`}</strong><small>{recruiter.workEmail}</small></span></label>;}):<EmptyState title="No active recruiters" description="Enable recruiter access on an active employee first."/>}</div></Modal><CandidateSubmissionModal open={Boolean(submissionJob)} onClose={()=>setSubmissionJob()} job={submissionJob} recruiters={recruiters} isOwner={isOwner}/></>;
}

export function AuditWorkspace() { return <ResourceWorkspace api={audit} title="Audit trail" meta="Governance" description="Immutable operational activity with request-level traceability." read={["handleGetAuditEvents"]} create={[]} columns={[{key:"createdAt",label:"Time",render:(v)=><DateText value={v} withTime/>},{key:"actorName",label:"Actor",render:(v,r)=>v||r.actor?.displayName||r.actorId},{key:"action",label:"Action"},{key:"entityType",label:"Entity"},{key:"requestId",label:"Request ID"}]} />; }

export function ReportsWorkspace() {
  const [report,setReport]=useState("candidates"); const [dates,setDates]=useState({startDate:"",endDate:""}); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const run=async()=>{setLoading(true);setError("");try{transitionResult(await reports.handleDownloadReport({report,...Object.fromEntries(Object.entries(dates).filter(([,v])=>v))}));}catch(e){setError(e.message);}finally{setLoading(false);}};
  return <main className="page-content"><PageHeading meta="Analytics" title="Reports & exports" description="Generate backend-authoritative operational datasets."/><section className="surface report-form"><Field label="Report"><select value={report} onChange={e=>setReport(e.target.value)}>{REPORT_TYPES.map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Start date"><input className="control" type="date" value={dates.startDate} onChange={e=>setDates({...dates,startDate:e.target.value})}/></Field><Field label="End date"><input className="control" type="date" value={dates.endDate} onChange={e=>setDates({...dates,endDate:e.target.value})}/></Field>{error&&<div className="auth-error">{error}</div>}<Button icon={FileDown} loading={loading} onClick={run}>Export report</Button></section></main>;
}
const WEEKDAYS = [{ value: 1, label: "Mon" }, { value: 2, label: "Tue" }, { value: 3, label: "Wed" }, { value: 4, label: "Thu" }, { value: 5, label: "Fri" }, { value: 6, label: "Sat" }, { value: 0, label: "Sun" }];

export function CompanyWorkspace() {
  const [company,setCompany]=useState(); const [form,setForm]=useState({name:"",timezone:"",workdayStartTime:"",workdayGraceMinutes:"",standardWorkMinutes:"",workweek:[]}); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{const value=await admin.handleGetCompany();setCompany(value);setForm({name:value?.name||"",timezone:value?.timezone||"",workdayStartTime:value?.settings?.workdayStartTime||"",workdayGraceMinutes:String(value?.settings?.workdayGraceMinutes??""),standardWorkMinutes:String(value?.settings?.standardWorkMinutes??""),workweek:value?.settings?.workweek||[1,2,3,4,5]});}catch(e){setError(e.message);}},[]); useEffect(()=>{load();},[load]);
  const toggleDay=(day)=>setForm(current=>({...current,workweek:current.workweek.includes(day)?current.workweek.filter(value=>value!==day):[...current.workweek,day].sort()}));
  // An empty shift start is sent as null, which is what switches punctuality
  // reporting back off on the dashboard rather than leaving a stale time behind.
  const save=async(e)=>{e.preventDefault();setSaving(true);setError("");try{transitionResult(await admin.handleUpdateCompany({name:form.name,timezone:form.timezone,settings:{workdayStartTime:form.workdayStartTime||null,...(form.workdayGraceMinutes!==""?{workdayGraceMinutes:Number(form.workdayGraceMinutes)}:{}),...(form.standardWorkMinutes!==""?{standardWorkMinutes:Number(form.standardWorkMinutes)}:{}),...(form.workweek.length?{workweek:form.workweek}:{})}}));await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
  return <main className="page-content"><PageHeading meta="Administration" title="Company settings" description="Tenant identity, timezone, and the workday shape used for server-side reporting."/>{!company&&!error?<Skeleton rows={4}/>:<form className="surface settings-form" onSubmit={save}>
    <Field label="Company name"><input className="control" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field>
    <Field label="IANA timezone"><input className="control" value={form.timezone} onChange={e=>setForm({...form,timezone:e.target.value})}/></Field>
    <div className="form-section-title"><strong>Workday</strong><small>Presence and punctuality on the overview dashboard are measured against these. Leave the shift start empty and punctuality is reported as unavailable rather than guessed.</small></div>
    <Field label="Shift start (24h, optional)" helper="For example 09:30. Clearing this hides punctuality from the dashboard."><input className="control" type="time" value={form.workdayStartTime} onChange={e=>setForm({...form,workdayStartTime:e.target.value})}/></Field>
    <Field label="Grace period (minutes)"><input className="control" type="number" min="0" max="240" value={form.workdayGraceMinutes} onChange={e=>setForm({...form,workdayGraceMinutes:e.target.value})}/></Field>
    <Field label="Full day (minutes)" helper="Days at or above this count as full days."><input className="control" type="number" min="1" max="1440" value={form.standardWorkMinutes} onChange={e=>setForm({...form,standardWorkMinutes:e.target.value})}/></Field>
    <Field label="Working days" helper="There is no holiday calendar, so absences are only counted on these days."><div className="tabs" role="group" aria-label="Working days">{WEEKDAYS.map(day=><button type="button" key={day.value} className={form.workweek.includes(day.value)?"active":""} aria-pressed={form.workweek.includes(day.value)} onClick={()=>toggleDay(day.value)}>{day.label}</button>)}</div></Field>
    {error&&<div className="auth-error">{error}</div>}<Button loading={saving}>Save settings</Button></form>}</main>;
}
