import { useEffect, useMemo, useState } from "react";
import * as api from "../../Services/apiCalling/crmApis";
import { CANDIDATE_LANGUAGES } from "../../constants/enums.constants";
import { transitionResult } from "../custom/apiBridge";
import { Button, Field, Modal } from "../custom/ui";

const blank = { jobOpeningId:"", recruiterEmployeeId:"", name:"", phone:"", candidateType:"NON_IT", email:"", qualification:"", languages:[], otherLanguage:"", location:"", remarks:"" };
const label = (value) => value.replaceAll("_", " ").replace(/\b\w/g, (character) => character.toUpperCase());

export default function CandidateSubmissionModal({ open, onClose, onSaved, job, candidate, jobs = [], recruiters = [], isOwner = false }) {
  const editing=Boolean(candidate);
  const [form,setForm]=useState(blank);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(open){setForm(candidate?{...blank,jobOpeningId:candidate.jobOpeningId?._id||candidate.jobOpeningId||"",name:candidate.name||"",phone:candidate.contact?.phone||"",candidateType:candidate.candidateType||"NON_IT",email:candidate.contact?.email||"",qualification:candidate.qualification||"",languages:candidate.languages||[],otherLanguage:candidate.otherLanguage||"",location:candidate.location||"",remarks:candidate.remarks||""}:{...blank,jobOpeningId:job?._id||"",candidateType:job?.jobType||"NON_IT"});setError("");}},[open,job,candidate]);
  const selectedJob=job||(candidate?.jobOpeningId&&typeof candidate.jobOpeningId==="object"?candidate.jobOpeningId:null)||jobs.find(item=>String(item._id)===String(form.jobOpeningId));
  const assignedIds=useMemo(()=>new Set((selectedJob?.assignedRecruiterIds||[]).map(item=>String(item?._id||item))),[selectedJob]);
  const eligibleRecruiters=isOwner?recruiters.filter(item=>assignedIds.has(String(item._id))):[];
  const toggleLanguage=(language)=>setForm(current=>({...current,languages:current.languages.includes(language)?current.languages.filter(item=>item!==language):[...current.languages,language]}));
  const submit=async(event)=>{event.preventDefault();if(!form.languages.length){setError("Select at least one language.");return;}setSaving(true);setError("");try{const contact={phone:form.phone,...(form.email?{email:form.email}:{})};if(editing){const payload={name:form.name,contact,candidateType:form.candidateType,languages:form.languages,qualification:form.qualification||null,otherLanguage:form.languages.includes("OTHER")&&form.otherLanguage?form.otherLanguage:null,location:form.location||null,remarks:form.remarks||null};transitionResult(await api.handleUpdateCrmCandidate(candidate._id,payload));}else{const payload={jobOpeningId:form.jobOpeningId,name:form.name,contact,candidateType:form.candidateType,languages:form.languages,consentGiven:true,source:"ASSIGNED_JOB_SUBMISSION",...(form.qualification?{qualification:form.qualification}:{}),...(form.otherLanguage?{otherLanguage:form.otherLanguage}:{}),...(form.location?{location:form.location}:{}),...(form.remarks?{remarks:form.remarks}:{}),...(isOwner&&form.recruiterEmployeeId?{recruiterEmployeeId:form.recruiterEmployeeId}:{})};transitionResult(await api.handleCreateCrmCandidate(payload));}onClose();await onSaved?.();}catch(requestError){setError(requestError.message);}finally{setSaving(false);}};
  return <Modal className="modal--employee" open={open} onClose={onClose} title={editing?"Edit candidate":"Submit candidate"} description={selectedJob?`${selectedJob.title} · ${selectedJob.vendorId?.name||selectedJob.companyName||selectedJob.location||"Assigned job"}`:"Add a candidate to an active job."} footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" form="candidate-submission-form" loading={saving}>{editing?"Save changes":"Submit candidate"}</Button></>}><form id="candidate-submission-form" className="form-grid" onSubmit={submit}>
    {!job&&!editing&&<Field label="Job opening" className="span-2"><select required value={form.jobOpeningId} onChange={event=>setForm({...form,jobOpeningId:event.target.value,recruiterEmployeeId:""})}><option value="">Select an active job</option>{jobs.filter(item=>item.status==="ACTIVE").map(item=><option key={item._id} value={item._id}>{item.title} · {item.vendorId?.name||item.companyName||item.location}</option>)}</select></Field>}
    <Field label="Name"><input className="control" required placeholder="e.g. Darshan Kumar" value={form.name} onChange={event=>setForm({...form,name:event.target.value})}/></Field>
    <Field label="Phone"><input className="control" type="tel" inputMode="tel" minLength="7" required placeholder="e.g. 9876543210" value={form.phone} onChange={event=>setForm({...form,phone:event.target.value})}/></Field>
    <Field label="IT / Non-IT"><select required value={form.candidateType} onChange={event=>setForm({...form,candidateType:event.target.value})}><option value="IT">IT</option><option value="NON_IT">Non-IT</option></select></Field>
    <Field label="Email"><input className="control" type="email" placeholder="e.g. employee@gmail.com" value={form.email} onChange={event=>setForm({...form,email:event.target.value})}/></Field>
    <Field label="Qualification"><input className="control" placeholder="e.g. B.Com, BE" value={form.qualification} onChange={event=>setForm({...form,qualification:event.target.value})}/></Field>
    <Field label="Location"><input className="control" placeholder="e.g. Bangalore" value={form.location} onChange={event=>setForm({...form,location:event.target.value})}/></Field>
    <div className="field span-2"><span className="field__label">Languages Known</span><div className="language-options">{CANDIDATE_LANGUAGES.map(language=><label className="language-option" key={language}><input type="checkbox" checked={form.languages.includes(language)} onChange={()=>toggleLanguage(language)}/><span>{label(language)}</span></label>)}</div></div>
    {form.languages.includes("OTHER")&&<Field label="Other language" className="span-2"><input className="control" placeholder="Enter another language" value={form.otherLanguage} onChange={event=>setForm({...form,otherLanguage:event.target.value})}/></Field>}
    {!editing&&isOwner&&selectedJob&&<Field label="Recruiter" helper="Optional; only recruiters assigned to this job are available." className="span-2"><select value={form.recruiterEmployeeId} onChange={event=>setForm({...form,recruiterEmployeeId:event.target.value})}><option value="">Unassigned</option>{eligibleRecruiters.map(recruiter=><option key={recruiter._id} value={recruiter._id}>{recruiter.displayName||`${recruiter.firstName} ${recruiter.lastName}`}</option>)}</select></Field>}
    <Field label="Remarks" className="span-2"><textarea placeholder="Add candidate remarks" value={form.remarks} onChange={event=>setForm({...form,remarks:event.target.value})}/></Field>
    {error&&<div className="auth-error span-2" role="alert">{error}</div>}<button type="submit" hidden/>
  </form></Modal>;
}
