const apiUserUrlPrefix = (import.meta.env.VITE_API_BASE_URL || "https://hrms-6sxu.onrender.com/api/v1").replace(/\/$/, "");

export const apiConstant = Object.freeze({
  healthLive: `${apiUserUrlPrefix}/health/live`,
  healthReady: `${apiUserUrlPrefix}/health/ready`,

  login: `${apiUserUrlPrefix}/auth/login`,
  refresh: `${apiUserUrlPrefix}/auth/refresh`,
  logout: `${apiUserUrlPrefix}/auth/logout`,
  logoutAll: `${apiUserUrlPrefix}/auth/logout-all`,
  forgotPassword: `${apiUserUrlPrefix}/auth/forgot-password`,
  requestOtp: `${apiUserUrlPrefix}/auth/request-otp`,
  verifyOtp: `${apiUserUrlPrefix}/auth/verify-otp`,
  resetPassword: `${apiUserUrlPrefix}/auth/reset-password`,
  changePassword: `${apiUserUrlPrefix}/auth/change-password`,
  sessions: `${apiUserUrlPrefix}/auth/sessions`,
  revokeSession: (id) => `${apiUserUrlPrefix}/auth/sessions/${id}`,
  me: `${apiUserUrlPrefix}/me`,

  company: `${apiUserUrlPrefix}/admin/companies`,

  employees: `${apiUserUrlPrefix}/employees`,
  employee: (id) => `${apiUserUrlPrefix}/employees/${id}`,
  employeeStatus: (id) => `${apiUserUrlPrefix}/employees/${id}/status`,
  employeeRecruiterAccess: (id) => `${apiUserUrlPrefix}/employees/${id}/recruiter-access`,
  employeeCredentialsReset: (id) => `${apiUserUrlPrefix}/employees/${id}/credentials/reset`,
  employeeBankDetails: (id) => `${apiUserUrlPrefix}/employees/${id}/bank-details`,
  employeeDocuments: (id) => `${apiUserUrlPrefix}/employees/${id}/documents`,

  attendanceMeState: `${apiUserUrlPrefix}/attendance/me/state`,
  attendanceClockIn: `${apiUserUrlPrefix}/attendance/me/clock-in`,
  attendanceBreak: `${apiUserUrlPrefix}/attendance/me/break`,
  attendanceResume: `${apiUserUrlPrefix}/attendance/me/resume`,
  attendanceClockOut: `${apiUserUrlPrefix}/attendance/me/clock-out`,
  attendanceMeHistory: `${apiUserUrlPrefix}/attendance/me/history`,
  attendanceRegister: `${apiUserUrlPrefix}/attendance`,
  attendanceCorrection: (id) => `${apiUserUrlPrefix}/attendance/${id}/correction`,

  leaveTypes: `${apiUserUrlPrefix}/leave-types`,
  leaveRequests: `${apiUserUrlPrefix}/leave-requests`,
  leaveRequestsMe: `${apiUserUrlPrefix}/leave-requests/me`,
  leaveApprove: (id) => `${apiUserUrlPrefix}/leave-requests/${id}/approve`,
  leaveReject: (id) => `${apiUserUrlPrefix}/leave-requests/${id}/reject`,
  leaveCancel: (id) => `${apiUserUrlPrefix}/leave-requests/${id}/cancel`,

  payrollPeriods: `${apiUserUrlPrefix}/payroll-periods`,
  payrollPeriod: (id) => `${apiUserUrlPrefix}/payroll-periods/${id}`,
  payrollCalculate: (id) => `${apiUserUrlPrefix}/payroll-periods/${id}/calculate`,
  payrollApprove: (id) => `${apiUserUrlPrefix}/payroll-periods/${id}/approve`,
  payrollReopen: (id) => `${apiUserUrlPrefix}/payroll-periods/${id}/reopen`,
  payrollLine: (id) => `${apiUserUrlPrefix}/payroll-lines/${id}`,
  payrollLineBreakdown: (id) => `${apiUserUrlPrefix}/payroll-lines/${id}/breakdown`,
  payrollLinePayslip: (id) => `${apiUserUrlPrefix}/payroll-lines/${id}/payslip`,
  payslipApprove: (id) => `${apiUserUrlPrefix}/payslips/${id}/approve`,
  payslipPublish: (id) => `${apiUserUrlPrefix}/payslips/${id}/publish`,
  payslipsMe: `${apiUserUrlPrefix}/payslips/me`,
  payslip: (id) => `${apiUserUrlPrefix}/payslips/${id}`,
  payslipDownload: (id) => `${apiUserUrlPrefix}/payslips/${id}/download`,

  vendors: `${apiUserUrlPrefix}/vendors`,
  vendor: (id) => `${apiUserUrlPrefix}/vendors/${id}`,
  vendorDocuments: (id) => `${apiUserUrlPrefix}/vendors/${id}/documents`,
  jobOpenings: `${apiUserUrlPrefix}/job-openings`,
  jobOpening: (id) => `${apiUserUrlPrefix}/job-openings/${id}`,
  jobOpeningStatus: (id) => `${apiUserUrlPrefix}/job-openings/${id}/status`,
  jobOpeningRecruiters: (id) => `${apiUserUrlPrefix}/job-openings/${id}/recruiters`,

  crmCandidates: `${apiUserUrlPrefix}/crm/candidates`,
  crmCandidate: (id) => `${apiUserUrlPrefix}/crm/candidates/${id}`,
  crmCandidateStage: (id) => `${apiUserUrlPrefix}/crm/candidates/${id}/stage`,
  crmCandidateInterview: (id) => `${apiUserUrlPrefix}/crm/candidates/${id}/interview`,
  crmCandidateHistory: (id) => `${apiUserUrlPrefix}/crm/candidates/${id}/history`,
  crmCandidateRecruiter: (id) => `${apiUserUrlPrefix}/crm/candidates/${id}/recruiter`,
  crmCandidateProfiles: `${apiUserUrlPrefix}/crm/candidate-profiles`,
  crmCandidateProfile: (id) => `${apiUserUrlPrefix}/crm/candidate-profiles/${id}`,
  crmCandidateProfilesAssign: `${apiUserUrlPrefix}/crm/candidate-profiles/assign`,
  crmCandidateProfileSubmit: (id) => `${apiUserUrlPrefix}/crm/candidate-profiles/${id}/submit`,
  crmMonitoring: `${apiUserUrlPrefix}/crm/monitoring`,
  crmMonitoringAnalytics: `${apiUserUrlPrefix}/crm/monitoring/analytics`,
  crmMonitoringDrilldown: `${apiUserUrlPrefix}/crm/monitoring/drilldown`,

  placements: `${apiUserUrlPrefix}/placements`,
  placement: (id) => `${apiUserUrlPrefix}/placements/${id}`,
  placementJoining: (id) => `${apiUserUrlPrefix}/placements/${id}/joining`,
  placementInvoiceOverride: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice-date-override`,
  placementInvoiceGenerate: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/generate`,
  placementInvoiceReady: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/ready`,
  placementInvoiceRaise: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/raise`,
  placementInvoiceReverse: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/reverse`,
  placementInvoiceDraft: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/draft`,
  placementInvoicePreview: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/preview`,
  placementInvoiceSave: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/save`,
  placementInvoiceDownload: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/download`,
  placementInvoicePaid: (id) => `${apiUserUrlPrefix}/placements/${id}/invoice/paid`,

  messagePartners: `${apiUserUrlPrefix}/messages/partners`,
  conversations: `${apiUserUrlPrefix}/messages/conversations`,
  conversation: (id) => `${apiUserUrlPrefix}/messages/conversations/${id}`,
  conversationMessages: (id) => `${apiUserUrlPrefix}/messages/conversations/${id}/messages`,
  conversationRead: (id) => `${apiUserUrlPrefix}/messages/conversations/${id}/read`,
  adminConversations: `${apiUserUrlPrefix}/admin/conversations`,

  notifications: `${apiUserUrlPrefix}/notifications`,
  notificationRead: (id) => `${apiUserUrlPrefix}/notifications/${id}/read`,
  notificationsReadAll: `${apiUserUrlPrefix}/notifications/read-all`,

  documents: `${apiUserUrlPrefix}/documents`,
  document: (id) => `${apiUserUrlPrefix}/documents/${id}`,
  documentDownload: (id) => `${apiUserUrlPrefix}/documents/${id}/download`,
  documentScanStatus: (id) => `${apiUserUrlPrefix}/documents/${id}/scan-status`,

  auditEvents: `${apiUserUrlPrefix}/audit-events`,
  dashboardAdmin: `${apiUserUrlPrefix}/reports/dashboard/admin`,
  dashboardAdminLive: `${apiUserUrlPrefix}/reports/dashboard/admin/live`,
  dashboardAdminDrilldown: `${apiUserUrlPrefix}/reports/dashboard/admin/drilldown`,
  dashboardRecruiter: `${apiUserUrlPrefix}/reports/dashboard/recruiter`,
  reportsExport: `${apiUserUrlPrefix}/reports/export`,
});

export { apiUserUrlPrefix };
export default apiConstant;
