import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Calculator, CheckCheck, Edit3, Eye, FilePlus2, RotateCcw, Send } from "lucide-react";
import * as payroll from "../../Services/apiCalling/payrollApis";
import * as payslips from "../../Services/apiCalling/payslipApis";
import * as employees from "../../Services/apiCalling/employeeApis";
import useIdempotencyKey from "../../hooks/useIdempotencyKey";
import useObjectIdParam from "../../hooks/useObjectIdParam";
import { transitionResult, unwrapCollection } from "../custom/apiBridge";
import { Button, DataTable, EmptyState, ErrorState, Field, Modal, Money, PageHeading, Skeleton, StatusBadge } from "../custom/ui";
import PayslipView from "./PayslipView";

export function PayrollPeriods() {
  const navigate=useNavigate(); const [form,setForm]=useState({periodMonth:new Date().getMonth()+1,periodYear:new Date().getFullYear(),employeeIds:[]}); const [employeeRows,setEmployeeRows]=useState(); const [periods,setPeriods]=useState(); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  const loadPeriods=useCallback(async()=>{try{setPeriods(unwrapCollection(await payroll.handleGetPayrollPeriods({page:1,limit:24})).items);}catch(e){setError(e.message);}},[]);
  useEffect(()=>{loadPeriods();},[loadPeriods]);
  useEffect(()=>{let active=true;employees.handleGetEmployees({page:1,limit:100,status:"ACTIVE"}).then(data=>{if(active)setEmployeeRows(unwrapCollection(data).items);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
  const toggleEmployee=id=>setForm(current=>({...current,employeeIds:current.employeeIds.includes(id)?current.employeeIds.filter(value=>value!==id):[...current.employeeIds,id]}));
  const create=async(e)=>{e.preventDefault();if(!form.employeeIds.length)return setError("Select at least one active employee.");setLoading(true);setError("");try{const data=transitionResult(await payroll.handleCreatePayrollPeriod({periodMonth:Number(form.periodMonth),periodYear:Number(form.periodYear),employeeIds:form.employeeIds}));navigate(`/payroll/${data._id}`);}catch(err){setError(err.message);await loadPeriods();}finally{setLoading(false);}};
  // A month can only be opened once, so point at the period already holding it.
  const clashing=(periods||[]).find(row=>Number(row.periodMonth)===Number(form.periodMonth)&&Number(row.periodYear)===Number(form.periodYear));
  return <main className="page-content"><PageHeading meta="Payroll" title="Start a payroll period" description="Create a draft for selected employees, then calculate and review server-produced lines."/><form className="surface settings-form payroll-create" onSubmit={create}><div className="form-grid"><Field label="Month"><input className="control" type="number" min="1" max="12" value={form.periodMonth} onChange={e=>setForm({...form,periodMonth:e.target.value})}/></Field><Field label="Year"><input className="control" type="number" min="2020" value={form.periodYear} onChange={e=>setForm({...form,periodYear:e.target.value})}/></Field><fieldset className="employee-picker span-2"><legend>Employees</legend><p>Select the active employees to include in this period.</p>{!employeeRows?<Skeleton rows={3}/>:employeeRows.length?employeeRows.map(row=><label key={row._id}><input type="checkbox" checked={form.employeeIds.includes(row._id)} onChange={()=>toggleEmployee(row._id)}/><span><strong>{row.displayName||[row.firstName,row.lastName].filter(Boolean).join(" ")||row.email}</strong><small>{row.employeeCode} · {row.department||"No department"}</small></span></label>):<EmptyState title="No active employees" description="Add or activate an employee before starting payroll."/>}</fieldset></div>{error&&<div className="auth-error">{error}{clashing&&<> <button type="button" className="link-button" onClick={()=>navigate(`/payroll/${clashing._id}`)}>Open the existing {clashing.periodMonth}/{clashing.periodYear} period</button></>}</div>}<Button icon={FilePlus2} loading={loading}>Create draft for {form.employeeIds.length||0} employees</Button></form>
    <section className="surface section-space"><div className="section-header"><div><h2>Payroll periods</h2><p>Every period opened for this company, newest first.</p></div></div>
      {!periods?<Skeleton rows={4}/>:periods.length?<DataTable rows={periods} columns={[{key:"periodMonth",label:"Period",render:(value,row)=>`${value}/${row.periodYear}`},{key:"employeeIds",label:"Employees",align:"right",render:(value)=>value?.length||0},{key:"status",label:"Status",render:StatusBadge}]} actions={row=><Button variant="quiet" onClick={()=>navigate(`/payroll/${row._id}`)}>Open</Button>}/>:<EmptyState title="No payroll periods yet" description="Create the first period using the form above."/>}
    </section></main>;
}

export function PayrollDetail() {
  const {id,isValid}=useObjectIdParam(); const [period,setPeriod]=useState(); const [error,setError]=useState(""); const [busy,setBusy]=useState(""); const [dialog,setDialog]=useState(); const [reason,setReason]=useState(""); const [lineForm,setLineForm]=useState({extraDeductions:"",reason:""}); const [payslipDialog,setPayslipDialog]=useState(); const {getKey,finish}=useIdempotencyKey();
  // The endpoint answers { period, lines }; flatten it so the period's own fields are readable here.
  const load=useCallback(async()=>{if(!isValid)return;try{const data=await payroll.handleGetPayrollPeriod(id);setPeriod(data?.period?{...data.period,lines:data.lines||[]}:data);setError("");}catch(e){setError(e.message);}},[id,isValid]); useEffect(()=>{load();},[load]);
  const act=async(name,fn)=>{setBusy(name);try{transitionResult(await fn());await load();}catch(e){setError(e.message);}finally{setBusy("");}};
  const approve=()=>{const attempt=`approve:${id}`;return act("approve",async()=>{const result=await payroll.handleApprovePayrollPeriod(id,getKey(attempt));if(result.ok)finish(attempt);setDialog();return result;});};
  const reopen=()=>{if(!reason.trim())return;const attempt=`reopen:${id}:${reason}`;act("reopen",async()=>{const result=await payroll.handleReopenPayrollPeriod(id,{reason},getKey(attempt));if(result.ok)finish(attempt);setDialog();setReason("");return result;});};
  const saveLine=async()=>{if(!lineForm.reason.trim())return;await act(`line-${dialog.row._id}`,()=>payroll.handleUpdatePayrollLine(dialog.row._id,lineForm));setDialog();};
  const payslipAction=(row)=>{
    const slip=row.payslip||{};const slipId=slip._id||row.payslipId;const status=slip.status||row.payslipStatus;
    if(!slipId)return <Button variant="quiet" loading={busy===`slip-${row._id}`} onClick={()=>act(`slip-${row._id}`,()=>payroll.handleGeneratePayslip(row._id))}>Generate payslip</Button>;
    // The owner may read a payslip at any stage, so viewing sits beside whatever step is next.
    const view=<Button variant="quiet" icon={Eye} onClick={()=>setPayslipDialog({id:slipId,mode:"view"})}>View payslip</Button>;
    // Approving is the last point a payslip can be corrected, so it opens for review first.
    if(status==="DRAFT")return <>{view}<Button variant="quiet" icon={CheckCheck} onClick={()=>setPayslipDialog({id:slipId,mode:"approve"})}>Review & approve</Button></>;
    if(status==="APPROVED")return <>{view}<Button variant="quiet" icon={Send} loading={busy===`publish-slip-${slipId}`} onClick={()=>act(`publish-slip-${slipId}`,()=>payslips.handlePublishPayslip(slipId))}>Publish slip</Button></>;
    return <>{view}<StatusBadge value={status}/></>;
  };
  const lines=period?.lines||period?.payrollLines||[];
  // Mirror the server's own state machine so an action is only offered when it would be accepted.
  const canCalculate=["DRAFT","REOPENED"].includes(period?.status);
  const editable=["CALCULATED","UNDER_REVIEW"].includes(period?.status);
  return <main className="page-content"><PageHeading meta="Payroll period" title={period?`${period.periodMonth}/${period.periodYear}`:"Payroll detail"} description="Amounts remain decimal strings and every workflow action is re-read from the server." actions={period&&<>{canCalculate&&<Button icon={Calculator} loading={busy==="calculate"} onClick={()=>act("calculate",()=>payroll.handleCalculatePayrollPeriod(id))}>{lines.length?"Recalculate":"Calculate"}</Button>}{period.status==="CALCULATED"&&<Button icon={CheckCheck} onClick={()=>setDialog({kind:"approve"})}>Approve</Button>}{["APPROVED","LOCKED"].includes(period.status)&&<Button variant="secondary" icon={RotateCcw} onClick={()=>setDialog({kind:"reopen"})}>Reopen</Button>}</>}/>{error?<ErrorState message={error} onRetry={load}/>:!period?<Skeleton rows={7}/>:<section className="surface"><div className="section-header"><div><h2>Payroll lines</h2><p><StatusBadge value={period.status}/></p></div></div>{lines.length?<DataTable rows={lines} columns={[{key:"employeeName",label:"Employee",render:(v,r)=>v||r.employee?.displayName||r.employeeId},{key:"workedHours",label:"Hours",align:"right"},{key:"grossPay",label:"Gross",align:"right",render:Money},{key:"deductions",label:"Deductions",align:"right",render:Money},{key:"netPay",label:"Net pay",align:"right",render:Money}]} actions={row=><div className="inline-actions">{editable&&<Button variant="quiet" icon={Edit3} onClick={()=>{setLineForm({extraDeductions:String(row.extraDeductions||""),reason:""});setDialog({kind:"line",row});}}>Edit deduction</Button>}{payslipAction(row)}</div>}/>:<EmptyState title="No calculated lines" description="Calculate this period to create server-authoritative payroll lines."/>}</section>}
    <Modal open={dialog?.kind==="approve"} onClose={()=>setDialog()} title="Approve payroll period" description="Approval makes the current calculation immutable until an authorized reopen." footer={<><Button variant="secondary" onClick={()=>setDialog()}>Cancel</Button><Button loading={busy==="approve"} onClick={approve}>Approve payroll</Button></>}><p className="dialog-copy">Review every payroll line before confirming this financial action.</p></Modal>
    <Modal open={dialog?.kind==="reopen"} onClose={()=>setDialog()} title="Reopen payroll period" description="A new revision will be recorded. Published financial history is not silently overwritten." footer={<><Button variant="secondary" onClick={()=>setDialog()}>Cancel</Button><Button loading={busy==="reopen"} disabled={!reason.trim()} onClick={reopen}>Reopen period</Button></>}><Field label="Reason"><textarea value={reason} required onChange={e=>setReason(e.target.value)}/></Field></Modal>
    <PayslipView payslipId={payslipDialog?.id} mode={payslipDialog?.mode} open={Boolean(payslipDialog)} onClose={()=>setPayslipDialog()} onApproved={load}/>
    <Modal open={dialog?.kind==="line"} onClose={()=>setDialog()} title="Adjust payroll deduction" description="Enter a decimal amount exactly as it should be sent to the server." footer={<><Button variant="secondary" onClick={()=>setDialog()}>Cancel</Button><Button loading={busy===`line-${dialog?.row?._id}`} disabled={!/^\d+(\.\d{1,2})?$/.test(lineForm.extraDeductions)||!lineForm.reason.trim()} onClick={saveLine}>Save adjustment</Button></>}><div className="form-stack"><Field label="Extra deductions" error={lineForm.extraDeductions&&!/^\d+(\.\d{1,2})?$/.test(lineForm.extraDeductions)?"Use a decimal amount with up to two places.":""}><input className="control" inputMode="decimal" value={lineForm.extraDeductions} onChange={e=>setLineForm({...lineForm,extraDeductions:e.target.value})}/></Field><Field label="Reason"><textarea value={lineForm.reason} onChange={e=>setLineForm({...lineForm,reason:e.target.value})}/></Field></div></Modal>
  </main>;
}

export function Payslips() {
  const [rows,setRows]=useState(); const [error,setError]=useState(""); const [payslipId,setPayslipId]=useState(); const load=useCallback(async()=>{try{setRows(unwrapCollection(await payslips.handleGetMyPayslips()).items);}catch(e){setError(e.message);}},[]);useEffect(()=>{load();},[load]);
  return <main className="page-content"><PageHeading meta="Compensation" title="My payslips" description="Open a payslip to read it in full, and download a PDF copy whenever you need one."/>{error?<ErrorState message={error} onRetry={load}/>:!rows?<Skeleton rows={5}/>:rows.length?<div className="card-grid">{rows.map(row=><article className="surface payslip-card" key={row._id}><StatusBadge value={row.status}/><h2>{row.periodLabel||`${row.periodMonth||""}/${row.periodYear||""}`}</h2><Money value={row.netPay}/><Button variant="secondary" icon={Eye} onClick={()=>setPayslipId(row._id)}>View payslip</Button></article>)}</div>:<EmptyState title="No published payslips" description="Published payslips will appear here."/>}
    <PayslipView payslipId={payslipId} open={Boolean(payslipId)} onClose={()=>setPayslipId()}/>
  </main>;
}
