import { useCallback, useEffect, useState } from "react";
import { ArrowRight, BadgeCheck, CalendarClock, Download, ReceiptIndianRupee, RotateCcw } from "lucide-react";
import * as api from "../../Services/apiCalling/placementApis";
import useIdempotencyKey from "../../hooks/useIdempotencyKey";
import { transitionResult, unwrapCollection } from "../custom/apiBridge";
import { Button, DataTable, DateText, EmptyState, ErrorState, Field, Modal, Money, PageHeading, Skeleton, StatusBadge } from "../custom/ui";
import InvoiceModal from "./InvoiceModal";

export default function Placements() {
  const [rows,setRows]=useState();const [error,setError]=useState("");const [busy,setBusy]=useState("");const [downloadingId,setDownloadingId]=useState("");const [dialog,setDialog]=useState();const [form,setForm]=useState({invoiceDueDate:"",invoiceReference:"",reason:""});const [invoiceFor,setInvoiceFor]=useState();const {getKey,finish}=useIdempotencyKey();
  const load=useCallback(async()=>{try{setRows(unwrapCollection(await api.handleGetPlacements({page:1,limit:100})).items);setError("");}catch(e){setError(e.message);}},[]);useEffect(()=>{load();},[load]);
  const run=async(row,fn)=>{setBusy(row._id);try{transitionResult(await fn());await load();}catch(e){setError(e.message);}finally{setBusy("");}};
  const open=(kind,row)=>{setForm({invoiceDueDate:row.invoiceDueDate?.slice(0,10)||"",invoiceReference:row.invoiceReference||"",reason:""});setDialog({kind,row});};
  const next=row=>{if(row.invoiceState==="GENERATED")return run(row,()=>api.handleMarkInvoiceReady(row._id));if(row.invoiceState==="READY_TO_RAISE")open("raise",row);};
  const download=async row=>{setDownloadingId(row._id);try{await api.handleDownloadInvoice(row._id);}catch(e){setError(e.message);}finally{setDownloadingId("");}};
  const submit=async()=>{const {kind,row}=dialog;if(kind==="override")await run(row,()=>api.handleOverridePlacementInvoiceDate(row._id,{invoiceDueDate:form.invoiceDueDate,reason:form.reason}));if(kind==="reverse")await run(row,()=>api.handleReverseInvoice(row._id,{reason:form.reason}));if(kind==="paid")await run(row,()=>api.handleMarkInvoicePaid(row._id));if(kind==="raise"){const attempt=`raise:${row._id}:${form.invoiceReference}`;await run(row,async()=>{const result=await api.handleRaiseInvoice(row._id,{invoiceReference:form.invoiceReference},getKey(attempt));if(result.ok)finish(attempt);return result;});}setDialog();};
  const valid=dialog?.kind==="override"?Boolean(form.invoiceDueDate&&form.reason.trim()):dialog?.kind==="reverse"?Boolean(form.reason.trim()):dialog?.kind==="paid"?true:dialog?.kind==="raise"?Boolean(dialog.row.invoiceAmount&&form.invoiceReference.trim()):false;
  const canDownload=state=>["GENERATED","READY_TO_RAISE","RAISED","PAID"].includes(state);
  return <main className="page-content placements-workspace"><PageHeading meta="Placements & invoices" title="Placement ledger" description="Joining dates and invoice amounts are synchronized from the candidate and job workflow."/>{error&&<ErrorState message={error} onRetry={load}/>} {!rows?<Skeleton rows={7}/>:rows.length?<section className="surface placements-table"><DataTable rows={rows} columns={[{key:"candidateName",label:"Candidate"},{key:"jobTitle",label:"Job"},{key:"clientName",label:"Client"},{key:"recruiterName",label:"Recruiter"},{key:"actualDoj",label:"Joined",render:DateText},{key:"invoiceDueDate",label:"Invoice due",render:DateText},{key:"invoiceAmount",label:"Amount",align:"right",render:Money},{key:"invoiceState",label:"State",render:StatusBadge}]} actions={row=><div className="inline-actions placement-row-actions">
    {["FUTURE_DUE","DUE"].includes(row.invoiceState)&&row.actualDoj&&row.invoiceAmount&&<Button icon={ReceiptIndianRupee} onClick={()=>setInvoiceFor(row._id)}>Generate invoice</Button>}
    {canDownload(row.invoiceState)&&<Button variant="quiet" icon={Download} loading={downloadingId===row._id} onClick={()=>download(row)}>Invoice PDF</Button>}
    {row.invoiceState==="GENERATED"&&<Button icon={ArrowRight} loading={busy===row._id} onClick={()=>next(row)}>Ready</Button>}
    {row.invoiceState==="READY_TO_RAISE"&&<Button icon={ReceiptIndianRupee} loading={busy===row._id} onClick={()=>next(row)}>Raise</Button>}
    {row.invoiceState==="RAISED"&&<Button icon={BadgeCheck} loading={busy===row._id} onClick={()=>open("paid",row)}>Mark paid</Button>}
    <Button variant="quiet" icon={CalendarClock} onClick={()=>open("override",row)}>Override due date</Button>
    {row.invoiceState==="RAISED"&&<Button variant="danger" icon={RotateCcw} onClick={()=>open("reverse",row)}>Reverse</Button>}
  </div>}/></section>:<EmptyState title="No placements" description="A selected CRM candidate creates a placement automatically."/>}
    <InvoiceModal placementId={invoiceFor} open={Boolean(invoiceFor)} onClose={()=>setInvoiceFor()} onSaved={load}/>
    <Modal open={Boolean(dialog)} onClose={()=>setDialog()} title={dialog?.kind==="override"?"Override invoice due date":dialog?.kind==="reverse"?"Reverse raised invoice":dialog?.kind==="paid"?"Mark invoice as paid":"Raise invoice"} description={dialog?.kind==="override"||dialog?.kind==="reverse"?"This financially significant change is recorded in the audit trail.":dialog?.kind==="paid"?"This records that the client has paid this invoice and updates the CRM revenue cards.":"The amount comes from vendor payment configured on the job opening."} footer={<><Button variant="secondary" onClick={()=>setDialog()}>Cancel</Button><Button variant={dialog?.kind==="reverse"?"danger":"primary"} loading={busy===dialog?.row?._id} disabled={!valid} onClick={submit}>Confirm action</Button></>}><div className="form-stack">{dialog?.kind==="override"&&<Field label="New invoice due date"><input className="control" type="date" value={form.invoiceDueDate} onChange={e=>setForm({...form,invoiceDueDate:e.target.value})}/></Field>}{dialog?.kind==="raise"&&<><div className="field"><span className="field__label">Invoice amount from job vendor payment</span><div className="control invoice-readonly-amount">{dialog.row.invoiceAmount?<Money value={dialog.row.invoiceAmount}/>:"Not configured"}</div></div><Field label="Invoice reference"><input className="control" value={form.invoiceReference} onChange={e=>setForm({...form,invoiceReference:e.target.value})}/></Field></>}{dialog?.kind==="paid"&&<div className="field"><span className="field__label">Amount</span><div className="control invoice-readonly-amount">{dialog.row.invoiceAmount?<Money value={dialog.row.invoiceAmount}/>:"Not configured"}</div></div>}{["override","reverse"].includes(dialog?.kind)&&<Field label="Reason"><textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></Field>}</div></Modal>
  </main>;
}
