const express = require('express');
const service = require('./employee.service');
const schemas = require('./employee.validator');
const { success } = require('../../common/http/response');
const { authenticate } = require('../../common/middleware/auth.middleware');
const { requireSuperAdmin } = require('../../common/middleware/access.middleware');
const { validate } = require('../../common/middleware/validate.middleware');
const { idempotency } = require('../../common/middleware/idempotency.middleware');
const router = express.Router();
router.use(authenticate);
router.get('/', requireSuperAdmin, validate(schemas.list), async (req, res) => success(res, await service.list(req.actor, req.validated.query)));
router.post('/', requireSuperAdmin, validate(schemas.create), async (req, res) => success(res, await service.create(req.actor, req.validated.body), 'Employee created', 201));
router.get('/:id', validate(schemas.id), async (req, res) => success(res, await service.get(req.actor, req.validated.params.id)));
router.patch('/:id', requireSuperAdmin, validate(schemas.update), async (req, res) => success(res, await service.update(req.actor, req.validated.params.id, req.validated.body), 'Employee updated'));
router.patch('/:id/status', requireSuperAdmin, validate(schemas.status), async (req, res) => success(res, await service.setStatus(req.actor, req.validated.params.id, req.validated.body), 'Employee status updated'));
router.patch('/:id/recruiter-access', requireSuperAdmin, validate(schemas.recruiterAccess), async (req, res) => success(res, await service.setRecruiterAccess(req.actor, req.validated.params.id, req.validated.body), 'Recruiter access updated'));
router.post('/:id/credentials/reset', requireSuperAdmin, validate(schemas.credentialReset), idempotency(), async (req, res) => { const result = await service.resetCredentials(req.actor, req.validated.params.id, req.validated.body?.newPassword); return success(res, result, result.mode === 'PASSWORD_SET' ? 'Password updated. The employee must change it at next sign-in.' : 'Credential reset instructions sent'); });
router.get('/:id/bank-details', validate(schemas.id), async (req, res) => success(res, await service.getBank(req.actor, req.validated.params.id)));
router.patch('/:id/bank-details', requireSuperAdmin, validate(schemas.bankUpdate), async (req, res) => { await service.updateBank(req.actor, req.validated.params.id, req.validated.body); return success(res, null, 'Bank details updated'); });
module.exports = router;
